sonar.projectKey=devops-cicd-security-platform
sonar.projectName=DevOps Security Platform
sonar.host.url=http://localhost:9000
sonar.login=squ_e084ffe40ccf0b80428ba1cf496f3dddf8335536

sonar.sources=.

sonar.inclusions=**/*.sh,**/*.yaml,**/*.yml,**/*.py

sonar.sourceEncoding=UTF-8